### ISSUE TITLE
vue3项目出现key未定义错误

### ISSUE THREAD

**Issue by weixiaojian** [saucxs/watermark#116]
VM2710:1 Uncaught (in promise) ReferenceError: key is not defined
    at loadMark (eval at node_modules/watermark-dom/index.js (index.js:1:1), <anonymous>:1:800)
    at watermark.init (eval at node_modules/watermark-dom/index.js (index.js:1:1), <anonymous>:1:7098)
    at Proxy.mounted (AppMain.vue:10:15)
    at runtime-core.esm-bundler.js:2739:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2713:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:343:32)
    at flushJobs (runtime-core.esm-bundler.js:397:9)

**Comment by DragonGoBC** [comment]
我也出现了这个问题，请问怎么解决了

**Comment by weixiaojian** [comment]
后面用watermark.js来实现了
[watermark.zip](https://github.com/saucxs/watermark-dom/files/15140646/watermark.zip)

**Comment by xiaohe0601** [comment]
可以试试 [watermark-lite](https://github.com/xiaohe0601/watermark-lite)
